125 categorycontroller
14A-A-Lyedlik-Devs/Gump pull request #274
Opened 2023-03-24 12:38 UTC by Sylvester2003

2023-03-24 12:46 UTC, ExAtom requested changes

2023-03-24 12:46 UTC, ExAtom commented on apps/backend/src/Gump.WebApi/Controllers/CategoryController.cs
> +	public IActionResult CreateCategory([FromBody] CategoryModel category) => this.Run(() =>
Erre kéne egy Dto, ami csak a name-et várja

2023-03-24 12:47 UTC, Rettend submitted a review, later dismissed
...
i guess progress

2023-03-24 12:47 UTC, Rettend commented
szia ati

2023-03-26 11:40 UTC, MAttila42 approved these changes

2023-03-26 11:54 UTC, merged