127 recipecontroller
14A-A-Lyedlik-Devs/Gump pull request #311
Opened 2023-03-31 18:58 UTC by Rettend

2023-03-31 18:59 UTC, Rettend commented
nem tudtam leellenőrizni postmannal

2023-03-31 19:50 UTC, MAttila42 requested changes

2023-03-31 19:50 UTC, MAttila42 commented on apps/backend/src/Gump.WebApi/Controllers/RecipeController.cs
> +			return Forbid();
Ez inkább unauthorized, mert a többinél is úgy van

2023-03-31 19:50 UTC, MAttila42 commented on apps/backend/src/Gump.WebApi/Controllers/RecipeController.cs
> +			modifiedRecipe = recipeRepository.GetById(update.Id);
Ez meg mégis mi a jó isten? xd
Először is a newRecipe-t ez az if fölé kéne hozni, majd szimplán meg kéne hívni a repository update metódusát, ha moderátor és nem a sajátja. Returnölni egy okét és kész. Itt így nem történik abszolút semmi

2023-03-31 19:50 UTC, MAttila42 commented on apps/backend/src/Gump.WebApi/Controllers/RecipeController.cs
> +		if (id != user.Id)
`&& !user.IsModerator`

2023-04-02 14:46 UTC, MAttila42 requested changes

2023-04-02 14:46 UTC, MAttila42 commented on apps/backend/src/Gump.WebApi/Controllers/RecipeController.cs
> +
Innen miért lett eltöntetve a create? Tedd vissza

2023-04-02 14:46 UTC, MAttila42 commented on apps/backend/src/Gump.WebApi/Controllers/RecipeController.cs
> +
Az if után, de az Ok előtt

2023-04-03 07:01 UTC, MAttila42 approved these changes

2023-04-03 07:01 UTC, merged